# Generated by Django 3.0.2 on 2020-01-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_auto_20200117_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
