version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn -c /home/app/web/gunicorn_conf.py mysite.wsgi:application
#    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --access-logfile /home/app/web/gunicorn-access.log --log-file /home/app/web/gunicorn-error.log -w 1 --threads 12
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume: